In [1]:
import numpy as np
import numpy as np
from scipy import misc
import matplotlib.pyplot as plt

In [3]:
arreglo_numeros = np.array([1,2,3])
print(arreglo_numeros)

[1 2 3]


In [4]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
np.zeros((1))

array([0.])

In [6]:
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [7]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [8]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.empty((5))
np.empty((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [11]:
np.eye((4))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
np.arange(3)

array([0, 1, 2])

In [13]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [14]:
np.arange(3,50)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [16]:
print(np.arange(12))
print(np.arange(4,20,2))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 4  6  8 10 12 14 16 18]


In [19]:
arreglo_dimension = np.array([(1,2,3), (4,5,6)])
print(arreglo_dimension.shape)

(2, 3)


In [21]:
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [23]:
np.ones_like(np.arange(6).reshape(3,2))
np.ones_like(np.arange(3))

array([1, 1, 1])

In [24]:
np.arange(24).reshape(4,3,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [25]:
np.arange(10000)

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [27]:
np.arange(10000).reshape(100,10,10)

array([[[   0,    1,    2, ...,    7,    8,    9],
        [  10,   11,   12, ...,   17,   18,   19],
        [  20,   21,   22, ...,   27,   28,   29],
        ...,
        [  70,   71,   72, ...,   77,   78,   79],
        [  80,   81,   82, ...,   87,   88,   89],
        [  90,   91,   92, ...,   97,   98,   99]],

       [[ 100,  101,  102, ...,  107,  108,  109],
        [ 110,  111,  112, ...,  117,  118,  119],
        [ 120,  121,  122, ...,  127,  128,  129],
        ...,
        [ 170,  171,  172, ...,  177,  178,  179],
        [ 180,  181,  182, ...,  187,  188,  189],
        [ 190,  191,  192, ...,  197,  198,  199]],

       [[ 200,  201,  202, ...,  207,  208,  209],
        [ 210,  211,  212, ...,  217,  218,  219],
        [ 220,  221,  222, ...,  227,  228,  229],
        ...,
        [ 270,  271,  272, ...,  277,  278,  279],
        [ 280,  281,  282, ...,  287,  288,  289],
        [ 290,  291,  292, ...,  297,  298,  299]],

       ...,

       [[9700, 9701, 970

In [28]:
#Sumas
a = np.array([10,10,10])
b = np.array([5,5,5])

print(a+b)

[15 15 15]


In [29]:
#Resta
print(a-b)

[5 5 5]


In [30]:
#Multiplicacion
print(a*b)

[50 50 50]


In [31]:
#Division
print(a/b)

[2. 2. 2.]


In [36]:

#Operaciones
arreglo_diez_ocho = np.arange(18)
print(arreglo_diez_ocho / 2)
print(arreglo_diez_ocho % 2)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5]
[0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]


In [37]:
#Expresiones
print(arreglo_diez_ocho > 9)

[False False False False False False False False False False  True  True
  True  True  True  True  True  True]


In [47]:
#Multiplicacion de varias dimensiones
A = np.arange(4).reshape(2,2) #np.array([[0,1],[2,3]])
print(A)
B = np.arange(4,8).reshape(2,2) #np.array([[4,5],[6,7]])
print(B)

print(A > B)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]
[[False False]
 [False False]]


In [40]:
np.arange(4).reshape(2,2)

array([[0, 1],
       [2, 3]])

In [44]:
np.arange(4,8).reshape(2,2)

array([[4, 5],
       [6, 7]])

In [49]:
#Multiplicacion dot
A.dot(B)
np.dot(A,B)

array([[ 6,  7],
       [26, 31]])

In [50]:
arreglo_tres = np.arange(3)
arreglo_tres *= 3
print(arreglo_tres)

[0 3 6]


In [54]:
#Operaciones conocidas en los arreglos

arreglo_diez = np.arange(10)

print(arreglo_diez)
print(arreglo_diez.sum())
print(arreglo_diez.min())
print(arreglo_diez.max())



[0 1 2 3 4 5 6 7 8 9]
45
0
9


In [57]:
arreglo_tres_cuatro = np.arange(12).reshape(3,4)
print(arreglo_tres_cuatro)
print(arreglo_tres_cuatro.sum(axis=0)) #sumando en x
print(arreglo_tres_cuatro.sum(axis=1)) #sumando en y


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[12 15 18 21]
[ 6 22 38]


In [59]:
# Universal functions
# Radianes
angulos_cero_noventa = np.array([0,30,45,60,90])
print(angulos_cero_noventa)
angulos_cero_noventa_radianes = angulos_cero_noventa * np.pi/180
print(angulos_cero_noventa_radianes)

[ 0 30 45 60 90]
[0.         0.52359878 0.78539816 1.04719755 1.57079633]


In [60]:
#Funcion seno
print(np.sin(angulos_cero_noventa))

[ 0.         -0.98803162  0.85090352 -0.30481062  0.89399666]


In [61]:
print(np.cos(angulos_cero_noventa))

[ 1.          0.15425145  0.52532199 -0.95241298 -0.44807362]


In [62]:
print(np.tan(angulos_cero_noventa))

[ 0.         -6.4053312   1.61977519  0.32004039 -1.99520041]


In [69]:
arreglo_diez = np.random.rand(30)*10
print(arreglo_diez)
print(np.mean(arreglo_diez)) #media
print(np.median(arreglo_diez)) #mediana

[4.30612645 6.65271041 7.88799945 8.53121484 8.77302107 6.17220597
 4.61637582 8.65467831 4.94095783 1.78715804 5.9073669  6.61835134
 4.73056865 9.73060277 2.55497532 8.44263045 3.22069188 8.9374504
 0.22561872 8.41331839 0.43661875 9.7387624  8.67441827 2.15167383
 4.18352468 6.53665957 1.34352335 4.22855974 6.23151957 9.17615974]
5.793514763448874
6.201862769760254


In [71]:
#desviacion estandas
print(np.std(arreglo_diez))

2.841684979599299


In [72]:
#varianza
print(np.var(arreglo_diez))

8.075173523280267


In [75]:
#salarios
salarios = np.genfromtxt('data/salarios.csv', delimiter=",")
print(salarios)
print(salarios.shape)

[[ 1.  3.  4.  5.  4.  3.  2.  2. 31. 33. 12.  1.  3.  4. 99.]
 [ 1.  3.  4.  5.  4.  3.  2.  2. 31. 33. 12.  1.  3.  4. 99.]]
(2, 15)


In [91]:
# Slice and Dice
arreglo_once_cuadrado = np.arange(11)**2
print(arreglo_once_cuadrado)
print(arreglo_once_cuadrado[0])
print(arreglo_once_cuadrado[0:3])
print(arreglo_once_cuadrado[-3])
print(arreglo_once_cuadrado[2:-3])
print(arreglo_once_cuadrado[-8:-1])
print(arreglo_once_cuadrado[1:])
print(arreglo_once_cuadrado[:5])
print(arreglo_once_cuadrado[2:8])
print(arreglo_once_cuadrado[2:8:4])
print(arreglo_once_cuadrado[2:8:4])
print(arreglo_once_cuadrado[:10:2])
print(arreglo_once_cuadrado[::-1])


[  0   1   4   9  16  25  36  49  64  81 100]
0
[0 1 4]
64
[ 4  9 16 25 36 49]
[ 9 16 25 36 49 64 81]
[  1   4   9  16  25  36  49  64  81 100]
[ 0  1  4  9 16]
[ 4  9 16 25 36 49]
[ 4 36]
[ 4 36]
[ 0  4 16 36 64]
[100  81  64  49  36  25  16   9   4   1   0]


# Interaciones

In [86]:
estudiantes = np.array([('Caro','Cristian', 'felipe'), (1,2,3,4),(6.5, 7.5)])

In [87]:
estudiantes

array([('Caro', 'Cristian', 'felipe'), (1, 2, 3, 4), (6.5, 7.5)],
      dtype=object)

In [88]:
estudiantes.shape

(3,)

In [26]:
for estudiantes in estudiantes.flatten():
    print(estudiantes)

['Caro', 'Cristian', 'felipe']
[1, 2, 3, 4]
[6.5, 7.5]


In [37]:
arreglo_tres_cuatro = np.arange(12).reshape(4,3)

In [30]:
arreglo_tres_cuatro

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [38]:
for i in np.nditer(arreglo_tres_cuatro):
    print(i)
    

0
1
2
3
4
5
6
7
8
9
10
11


In [42]:
#cambios dentro del arreglo
for i in np.nditer(arreglo_tres_cuatro, order = "F", op_flags=['readwrite']):
    print(i)
    i[...] = i*i
    print(i)

0
0
3
9
6
36
9
81
1
1
4
16
7
49
10
100
2
4
5
25
8
64
11
121


In [68]:
#reshape
paises_tuplas = np.array([('alemania', 'inglaterra', 'ecuador', 'argentina'),
                          ('mexico','ecuador','guatemala', 'venezuela')])

In [69]:
paises_tuplas

array([['alemania', 'inglaterra', 'ecuador', 'argentina'],
       ['mexico', 'ecuador', 'guatemala', 'venezuela']], dtype='<U10')

In [70]:
paises_tuplas

array([['alemania', 'inglaterra', 'ecuador', 'argentina'],
       ['mexico', 'ecuador', 'guatemala', 'venezuela']], dtype='<U10')

In [71]:
paises_tuplas[0][0]

'alemania'

In [72]:
paises_tuplas.flatten().shape

(8,)

In [73]:
paises_tuplas.T.flatten()

array(['alemania', 'mexico', 'inglaterra', 'ecuador', 'ecuador',
       'guatemala', 'argentina', 'venezuela'], dtype='<U10')

In [79]:
paises_tuplas

array([['alemania', 'inglaterra', 'ecuador', 'argentina'],
       ['mexico', 'ecuador', 'guatemala', 'venezuela']], dtype='<U10')

In [82]:
paises = np.array([('alemania', 'inglaterra', 'ecuador', 'argentina', 'mexico','ecuador',
                    'guatemala', 'venezuela', 'estados unidos', 'peru',
                   'chile', 'colombia')])

In [83]:
paises.reshape(-1,3,2) # 9 9 = X *3 X =9/3 = 3

array([[['alemania', 'inglaterra'],
        ['ecuador', 'argentina'],
        ['mexico', 'ecuador']],

       [['guatemala', 'venezuela'],
        ['estados unidos', 'peru'],
        ['chile', 'colombia']]], dtype='<U14')

In [85]:
paises.reshape(3,-1,2)

array([[['alemania', 'inglaterra'],
        ['ecuador', 'argentina']],

       [['mexico', 'ecuador'],
        ['guatemala', 'venezuela']],

       [['estados unidos', 'peru'],
        ['chile', 'colombia']]], dtype='<U14')

In [96]:
#Split
arreglo_split = np.arange(1,13)

In [97]:
arreglo_split

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [99]:
np.split(arreglo_split, 3)

[array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]

In [100]:
np.split(arreglo_split, [2,3,6,8])

[array([1, 2]),
 array([3]),
 array([4, 5, 6]),
 array([7, 8]),
 array([ 9, 10, 11, 12])]

In [102]:
paises = np.array([('alemania', 'inglaterra', 'ecuador', 'argentina', 'peru', 'chile')])

In [103]:
paises

array([['alemania', 'inglaterra', 'ecuador', 'argentina', 'peru',
        'chile']], dtype='<U10')

In [105]:
#horizontal split
np.hsplit(paises, 2)

[array([['alemania', 'inglaterra', 'ecuador']], dtype='<U10'),
 array([['argentina', 'peru', 'chile']], dtype='<U10')]

In [108]:
paises_2d = np.array([('alemania', 'inglaterra', 'ecuador'), ('argentina', 'peru', 'chile')])

In [111]:
np.vsplit(paises_2d,2)

[array([['alemania', 'inglaterra', 'ecuador']], dtype='<U10'),
 array([['argentina', 'peru', 'chile']], dtype='<U10')]

In [114]:
np.hsplit(paises_2d,3)

[array([['alemania'],
        ['argentina']], dtype='<U10'), array([['inglaterra'],
        ['peru']], dtype='<U10'), array([['ecuador'],
        ['chile']], dtype='<U10')]