In [1]:
import numpy as np

In [2]:
arreglo = np.arange(16).reshape(4,4)

In [3]:
print(arreglo)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [4]:
indice_booleano_mayores_ocho = arreglo > 8

In [5]:
print(indice_booleano_mayores_ocho)

[[False False False False]
 [False False False False]
 [False  True  True  True]
 [ True  True  True  True]]


In [6]:
print(arreglo[indice_booleano_mayores_ocho])

[ 9 10 11 12 13 14 15]


In [7]:
print(np.count_nonzero(indice_booleano_mayores_ocho))

7


In [8]:
print(np.sum(indice_booleano_mayores_ocho))

7


In [9]:
print(np.sum(indice_booleano_mayores_ocho, axis=1))

[0 0 3 4]


In [14]:
indice_booleano_mayor_veinte = arreglo < 0
print(np.any(indice_booleano_mayor_veinte))

False


In [18]:
indice_booleano_mayor_cero = arreglo > 0
print(np.all(indice_booleano_mayor_cero))
print(np.all(indice_booleano_mayor_cero, axis=1))

False
[False  True  True  True]
